version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innerview-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:rootpassword@db:3306/innerview_ilhabela
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - innerview-network
    command: sleep infinity

  db:
    image: mysql:8.0
    container_name: innerview-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=innerview_ilhabela
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - innerview-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: innerview-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - innerview-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  innerview-network:
    driver: bridge

volumes:
  db-data:
  redis-data: 