/**
 * Enums compartilhados para toda a aplicação.
 * Estes enums servem como alternativa às importações diretas do Prisma,
 * facilitando os testes e reduzindo acoplamento.
 */

export enum Status {
  PENDENTE = 'PENDENTE',
  AGENDADO = 'AGENDADO',
  ATIVO = 'ATIVO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
}

export enum CargoUsuario {
  ADMIN = 'ADMIN',
  PROFESSOR = 'PROFESSOR',
  ESPECIALISTA = 'ESPECIALISTA',
  COORDENADOR = 'COORDENADOR',
  DIRETOR = 'DIRETOR',
  ADMINISTRADOR = 'ADMINISTRADOR',
}

export enum CargoEquipe {
  COORDENADOR = 'COORDENADOR',
  ESPECIALISTA = 'ESPECIALISTA',
  PROFESSOR = 'PROFESSOR',
  CONSELHEIRO = 'CONSELHEIRO',
  PSICOLOGO = 'PSICOLOGO',
  OUTRO = 'OUTRO',
}

export enum Genero {
  M = 'M',
  F = 'F',
  OUTRO = 'OUTRO',
}

export enum Turno {
  MANHA = 'MANHA',
  TARDE = 'TARDE',
  NOITE = 'NOITE',
  INTEGRAL = 'INTEGRAL',
}

export enum TipoResponsavel {
  MAE = 'MAE',
  PAI = 'PAI',
  AVOA = 'AVOA',
  AVO = 'AVO',
  TIA = 'TIA',
  TIO = 'TIO',
  IRMA = 'IRMA',
  IRMAO = 'IRMAO',
  TUTOR = 'TUTOR',
  OUTRO = 'OUTRO',
}

export enum Plataforma {
  GOOGLE_CLASSROOM = 'GOOGLE_CLASSROOM',
  MICROSOFT_TEAMS = 'MICROSOFT_TEAMS',
  LTI = 'LTI',
  PERSONALIZADO = 'PERSONALIZADO',
}

export enum TipoComunicacao {
  EMAIL = 'EMAIL',
  TELEFONE = 'TELEFONE',
  PRESENCIAL = 'PRESENCIAL',
  CARTA = 'CARTA',
  OUTRO = 'OUTRO',
}

export enum StatusComunicacao {
  RASCUNHO = 'RASCUNHO',
  ENVIADO = 'ENVIADO',
  ENTREGUE = 'ENTREGUE',
  LIDO = 'LIDO',
  RESPONDIDO = 'RESPONDIDO',
  FALHA = 'FALHA',
}

export enum Prioridade {
  BAIXA = 'BAIXA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE',
}

export enum TipoNotificacao {
  REUNIAO_AGENDADA = 'REUNIAO_AGENDADA',
  LEMBRETE_REUNIAO = 'LEMBRETE_REUNIAO',
  ENCAMINHAMENTO_ATRIBUIDO = 'ENCAMINHAMENTO_ATRIBUIDO',
  PRAZO_PROXIMO = 'PRAZO_PROXIMO',
  PRAZO_VENCIDO = 'PRAZO_VENCIDO',
  MENSAGEM_RECEBIDA = 'MENSAGEM_RECEBIDA',
  ESTUDANTE_ATUALIZADO = 'ESTUDANTE_ATUALIZADO',
  AVALIACAO_ADICIONADA = 'AVALIACAO_ADICIONADA',
  INTERVENCAO_ATUALIZADA = 'INTERVENCAO_ATUALIZADA',
  CONVITE_EQUIPE = 'CONVITE_EQUIPE',
}

export enum Nivel {
  BAIXO = 'BAIXO',
  MODERADO = 'MODERADO',
  ALTO = 'ALTO',
  MUITO_ALTO = 'MUITO_ALTO',
}

export enum CategoriaDificuldade {
  LEITURA = 'LEITURA',
  ESCRITA = 'ESCRITA',
  MATEMATICA = 'MATEMATICA',
  ATENCAO = 'ATENCAO',
  COMPORTAMENTO = 'COMPORTAMENTO',
  COMUNICACAO = 'COMUNICACAO',
  COORDENACAO_MOTORA = 'COORDENACAO_MOTORA',
  MEMORIA = 'MEMORIA',
  ORGANIZACAO = 'ORGANIZACAO',
  OUTRO = 'OUTRO',
}

export enum CategoriaInstrumento {
  ACADEMICO = 'ACADEMICO',
  COMPORTAMENTAL = 'COMPORTAMENTAL',
  SOCIOEMOCIONAL = 'SOCIOEMOCIONAL',
  COGNITIVO = 'COGNITIVO',
  LINGUAGEM = 'LINGUAGEM',
  MOTOR = 'MOTOR',
  ATENCAO = 'ATENCAO',
  OUTRO = 'OUTRO',
}

export enum TipoIndicador {
  ESCALA_LIKERT = 'ESCALA_LIKERT',
  SIM_NAO = 'SIM_NAO',
  NUMERICO = 'NUMERICO',
  MULTIPLA_ESCOLHA = 'MULTIPLA_ESCOLHA',
  TEXTO_LIVRE = 'TEXTO_LIVRE',
}

export enum NivelIntervencao {
  UNIVERSAL = 'UNIVERSAL',
  SELETIVO = 'SELETIVO',
  INTENSIVO = 'INTENSIVO',
}

export enum AreaIntervencao {
  LEITURA = 'LEITURA',
  ESCRITA = 'ESCRITA',
  MATEMATICA = 'MATEMATICA',
  COMPORTAMENTO = 'COMPORTAMENTO',
  ATENCAO = 'ATENCAO',
  SOCIOEMOCIONAL = 'SOCIOEMOCIONAL',
  LINGUAGEM = 'LINGUAGEM',
  OUTRO = 'OUTRO',
}

export enum FrequenciaAplicacao {
  DIARIA = 'DIARIA',
  SEMANAL = 'SEMANAL',
  QUINZENAL = 'QUINZENAL',
  MENSAL = 'MENSAL',
  PERSONALIZADA = 'PERSONALIZADA',
}

export enum TipoMeta {
  ACADEMICA = 'ACADEMICA',
  COMPORTAMENTAL = 'COMPORTAMENTAL',
  SOCIOEMOCIONAL = 'SOCIOEMOCIONAL',
  COGNITIVA = 'COGNITIVA',
  LINGUAGEM = 'LINGUAGEM',
  MOTORA = 'MOTORA',
  ATENCAO = 'ATENCAO',
  OUTRA = 'OUTRA',
}

export enum StatusMeta {
  NAO_INICIADA = 'NAO_INICIADA',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  ATINGIDA = 'ATINGIDA',
  NAO_ATINGIDA = 'NAO_ATINGIDA',
  CANCELADA = 'CANCELADA',
}
